// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqxxgrovwklafyxafpoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxeHhncm92d2tsYWZ5eGFmcG95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTI0MjcsImV4cCI6MjA3NDQ2ODQyN30.T11O4rrRdS1OfqmaJnStAtOFQT0f1OJRWM2jkeBTkvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});